Angle/Models/DocumentUpload.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations.Schema;
namespace Angle.Models
{
    public class DocumentUpload
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DocumentUploadID { get; set; }
        public DateTime DateUpload { get; set; }
        public string Module { get; set; }
        public string Attachment { get; set; }
        public int ModuleID { get; set; }

    }
}

Angle/Controllers/DocumentUploadController.cs
using AutoMapper;
using Angle.DTOs;
using Angle.Services;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Collections.Generic;

using Microsoft.Data.SqlClient;
using DocumentUpload = Angle.Models.DocumentUpload;

using System.Data;

namespace Angle.Controllers
{
    public class DocumentUploadController : Controller
    {
        private readonly IDocumentUploadService documentuploadService;
        private readonly IMapper mapper;

        public DocumentUploadController(IDocumentUploadService documentuploadService,
            IMapper mapper)
        {
            this.documentuploadService = documentuploadService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var data = await documentuploadService.GetAll();
            var listDocumentUpload = data.Select(x => mapper.Map<DocumentUploadDTO>(x)).ToList();
            return View(listDocumentUpload);
        }

        public async Task<IActionResult> FileUpload(List<IFormFile> files, string Module, int ModuleID)
        {
            var size = files.Sum(f => f.Length);
            int IDModulo = ModuleID;
            string Modulo = Module;
            var filePaths = new List<string>();
            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\files", formFile.FileName);
                    filePaths.Add(filePath);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                        SqlConnection conexion = new SqlConnection("Server=EC2AMAZ-9EP7VB3;Database=FTrackV2;User Id=sa; Password=asdf@1245");
                        conexion.Open();
                        string Attachment = formFile.FileName;

                        string cadena = "insert into [dbo].[FT_DocumentUpload]([DateUpload],[Module],[Attachment],[ModuleID]) values ('2021-05-02','" + Modulo + "','" + Attachment + "' ," + IDModulo + ")";
                        SqlCommand comando = new SqlCommand(cadena, conexion);
                        comando.ExecuteNonQuery();
                        conexion.Close();
                    }
                }
            }

            return RedirectToAction("Index", "Customer");
        }


        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsx", "application/vnd.openxmlformats officedocument.spreadsheetml.sheet"},  
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
        }

        public async Task<IActionResult> Download(string filename)
        {
            if (filename == null)
                return Content("filename not present");

            var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/files", filename);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(path), Path.GetFileName(path));
        }

        public async Task<IActionResult> CreateAsync()
        {

            ViewBag.Status = await documentuploadService.GetStatus();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(DocumentUploadDTO documentuploadDTO)
        {

            if (ModelState.IsValid)
            {

                var documentupload = mapper.Map<DocumentUpload>(documentuploadDTO);

                documentupload = await documentuploadService.Insert(documentupload);

                return RedirectToAction("Index");
            }

            return View(documentuploadDTO);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var documentupload = await documentuploadService.GetById(id.Value);

            if (documentupload == null)
                return NotFound();

            ViewBag.Status = await documentuploadService.GetStatus();
            var documentuploadDTO = mapper.Map<DocumentUploadDTO>(documentupload);
            return View(documentuploadDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DocumentUploadDTO documentuploadDTO)
        {
            if (ModelState.IsValid)
            {
                var documentupload = mapper.Map<DocumentUpload>(documentuploadDTO);

                documentupload = await documentuploadService.Update(documentupload);

                return RedirectToAction("Index");
            }

            return View(documentuploadDTO);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var documentupload = await documentuploadService.GetById(id.Value);

            if (documentupload == null)
                return NotFound();

            var documentuploadDTO = mapper.Map<DocumentUploadDTO>(documentupload);

            return View(documentuploadDTO);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            await documentuploadService.Delete(id.Value);

            return RedirectToAction("Index");
        }
    }
}

Angle/Views/DocumentUpload/Create.cshtml
@model Angle.DTOs.StatusDTO

@{ ViewData["Title"] = "Create"; }

<div class="content-heading">
    <div>
        Estatus
    </div>
    <div class="ml-auto">
        <div class="btn-group">
            <button class="btn btn-secondary dropdown-toggle dropdown-toggle-nocaret" type="button" data-toggle="dropdown">English</button>
            <div class="dropdown-menu dropdown-menu-right-forced animated fadeInUpShort" role="menu">
                <a class="dropdown-item" href="#" data-set-lang="en">English</a><a class="dropdown-item" href="#" data-set-lang="es">Spanish</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12">
        <div class="card card-default">
            <div class="card-header">
                <ol class="breadcrumb breadcrumb px-0 pb-0">
                    <li class="breadcrumb-item">
                        <a href="#">Parametrizaci&oacute;n</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="Index">Estatus</a>
                    </li>
                </ol>
            </div>


            <div class="card-body">
                <form asp-action="Create" id="formEstatus" data-parsley-validate="" novalidate="">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="StatusName" class="control-label"></label>
                                <input asp-for="StatusName" class="form-control" required />
                                <span asp-validation-for="StatusName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="StatusColor" class="control-label"></label>
                                <select asp-for="StatusColor" class="form-control form-control-lg" required>
                                    <option value="info">Seleccionar</option>
                                    <option value="success">Verde</option>
                                    <option value="warning">Amarillo</option>
                                    <option value="danger">Rojo</option>
                                </select>
                                <span asp-validation-for="StatusColor" class="text-danger"></span>
                            </div>
                        </div>
                    </div>    
                    <div class="form-group">
                        <input type="submit" value="Guardar" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Listar Estatus</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<environment names="Development">
    <script src="~/vendor/parsleyjs/dist/parsley.js"></script>
    <script src="~/vendor/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        Parsley.addMessages('en', {
            required: "Valor requerido.",
        });
        Parsley.setLocale('en');

    </script>
</environment>
<environment names="Staging,Production">
    <script src="~/vendor/parsleyjs/dist/parsley.js"></script>
    <script src="~/vendor/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        Parsley.addMessages('en', {
            required: "Valor requerido.",
        });
        Parsley.setLocale('en');

    </script>
</environment>

}

Angle/Views/DocumentUpload/Details.cshtml
@model Angle.DTOs.StatusDTO

@{ ViewData["Title"] = "Details"; }

<h1>Details</h1>

<div>
    <h4>Status</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.StatusID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Angle/Views/DocumentUpload/Edit.cshtml
@model Angle.DTOs.StatusDTO

@{ ViewData["Title"] = "Edit"; }

<div class="content-heading">
    <div>
        Estatus
    </div>
    <div class="ml-auto">
        <div class="btn-group">
            <button class="btn btn-secondary dropdown-toggle dropdown-toggle-nocaret" type="button" data-toggle="dropdown">English</button>
            <div class="dropdown-menu dropdown-menu-right-forced animated fadeInUpShort" role="menu">
                <a class="dropdown-item" href="#" data-set-lang="en">English</a><a class="dropdown-item" href="#" data-set-lang="es">Spanish</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12">
        <div class="card card-default">
            <div class="card-header">
                <ol class="breadcrumb breadcrumb px-0 pb-0">
                    <li class="breadcrumb-item">
                        <a href="#">Parametrizaci&oacute;n</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="">Estatus</a>
                    </li>
                </ol>
            </div>


            <div class="card-body">
                <form asp-action="Edit"  data-parsley-validate="" novalidate="">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="StatusID" />
                    <div class="row">
                        <div class="col-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="StatusName" class="control-label"></label>
                                <input asp-for="StatusName" class="form-control" required />
                                <span asp-validation-for="StatusName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="StatusColor" class="control-label"></label>
                                <select asp-for="StatusColor" class="form-control form-control-lg" required>
                                    <option value="info">Seleccionar</option>
                                    <option value="success">Verde</option>
                                    <option value="warning">Amarillo</option>
                                    <option value="danger">Rojo</option>
                                </select>
                                <span asp-validation-for="StatusColor" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Guardar" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Listar Estatus</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<environment names="Development">
    <script src="~/vendor/parsleyjs/dist/parsley.js"></script>
    <script src="~/vendor/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        Parsley.addMessages('en', {
            required: "Valor requerido.",
        });
        Parsley.setLocale('en');

    </script>
</environment>
<environment names="Staging,Production">
    <script src="~/vendor/parsleyjs/dist/parsley.js"></script>
    <script src="~/vendor/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        Parsley.addMessages('en', {
            required: "Valor requerido.",
        });
        Parsley.setLocale('en');

    </script>
</environment>

}

Angle/Views/DocumentUpload/Index.cshtml
@model IEnumerable<Angle.DTOs.DocumentUploadDTO>

@using Microsoft.AspNetCore.Http.Extensions
@{ ViewData["Title"] = "Index";
    string words = Context.Request.GetEncodedUrl();

    string[] ID = words.Split('/');
    string Modulo = ID[5];
    string IDModulo = Modulo.Substring(Modulo.Length - 1, 1);
    Modulo = Modulo.Substring(0, Modulo.Length - 1);
}



<div class="content-heading">
    <div>
        Documentos
    </div>
    <div class="ml-auto">
        <div class="btn-group">
            <button class="btn btn-secondary dropdown-toggle dropdown-toggle-nocaret" type="button" data-toggle="dropdown">English</button>
            <div class="dropdown-menu dropdown-menu-right-forced animated fadeInUpShort" role="menu">
                <a class="dropdown-item" href="#" data-set-lang="en">English</a><a class="dropdown-item" href="#" data-set-lang="es">Spanish</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12">
        <div class="card card-default">
            <div class="card-header">
                <ol class="breadcrumb breadcrumb px-0 pb-0">
                    <li class="breadcrumb-item">
                        <a href="#">Operaci&oacute;n</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="Index">Documentos</a>
                    </li>
                </ol>
            </div>
            <div class="card-body">
                <div class="col-lg-12">
                    <form method="post" enctype="multipart/form-data" asp-controller="DocumentUpload" asp-action="FileUpload">
                        <div class="form-group">
                            <div class="col-md-10">
                                <p>Upload one or more files</p>
                                <input type="file" name="files" multiple />
                                <input type="text" value="2021-01-01" name="DateUpload" hidden />
                                <input type="text" value="@Modulo" name="Module" hidden />
                                <input type="text" value="@IDModulo" name="ModuleID" hidden />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <input type="submit" value="Upload" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



<environment names="Development">

    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript">
        var pathname = window.location.pathname;
        var vars = pathname.split("/");
        $('#agregarDocumento').attr('href', 'http://cpsqa.4track.tk/DocumentUpload/FileUpload/Customer' + vars[3]);

    </script>
</environment>
<environment names="Staging,Production">

    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript">
        var pathname = window.location.pathname;
        var vars = pathname.split("/");
        $('#agregarDocumento').attr('href', 'http://cpsqa.4track.tk/DocumentUpload/FileUpload/Customer' + vars[3]);

    </script>
</environment>